12 import project from git repo
taubyte/tau-cli pull request #19
Opened 2023-08-08 22:33 UTC by tafseer-khan

Demo: https://asciinema.org/a/3yCj34o7gc4frJDdHszdbDRwL

2023-08-09 14:05 UTC, samyfodil requested changes

2023-08-09 14:05 UTC, samyfodil commented on cli/commands/resources/project/delete.go
> +package project
unit test?

2023-08-09 14:05 UTC, samyfodil commented on cli/commands/resources/project/import.go
> +	endpoint := fmt.Sprintf("https://api.github.com/users/%s/repos", user)
I think you can do this properly with github go client as we're doing in auth

2023-08-10 22:44 UTC, arontaubyte requested changes

2023-08-10 22:44 UTC, arontaubyte commented on cli/commands/resources/project/delete.go
> +		prj, err := prjHandler.Get(projectName)
just one line it config.Projects().Get(projectName)

2023-08-10 22:47 UTC, merged